version: 0.2
       
phases:
  install:
    commands:
      - go get
  build:
    commands:
      - go build
artifacts:
  files:
    - 'cloudawsgo'
  name:     
    - name: cloudawsgo_${GOOS}_${GOARCH}_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)